[package]
name = "prost-arrow-derive"
authors = [ "Matt Forbes <matt.r.forbes@gmail.com>" ]
edition = "2021"
version = "0.0.1"

[lib]
proc-macro = true

[dependencies]
prettyplease = { version = "0.2" }
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
